"""Remove redundant field

Revision ID: 126ecfb9a15e
Revises: 914d6a435784
Create Date: 2020-08-23 12:21:35.593634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126ecfb9a15e'
down_revision = '914d6a435784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
